### ISSUE TITLE
[PROPOSAL] URL Queries to Struct or Map or other data structure

### ISSUE THREAD

**Issue by hadihammurabi** [ngamux/ngamux#18]
Need something like:
```go
type QueryStruct struct {
Page string
}

q := QueryStruct{}
err := c.Queries(&q)
```

to parse URL query string into struct

**Comment by fanchann** [comment]
hi @hadihammurabi,
is this what you mean?
https://goplay.space/#kBXhGw0MC1A

**Comment by hadihammurabi** [comment]
resolved at https://github.com/ngamux/ngamux/pull/21
