### ISSUE TITLE
[PROPOSAL] Wrap http.ResponseWriter and *http.Request in Context

### ISSUE THREAD

**Issue by hadihammurabi** [ngamux/ngamux#9]
Some reasons we need to wrap http.ResponseWriter and *http.Request is:
* cleaner route handler
* manage request and response in one place
* like most http router ([Fiber](https://docs.gofiber.io/api/ctx), [Echo](https://echo.labstack.com/guide/context/))

Then we need create one place that contains http.ResponseWriter and *http.Request inside that can manage both easily.
It could be like this.
```go
func IndexHandler(c *ngamux.Ctx) error {
}
```

If we see deeper, the Ctx type will be like this.
```go
type Ctx struct {
  rw http.ResponseWriter
  r *http.Request
}

// request
func (c Ctx) GetParam(key string) string
func (c Ctx) GetJSON(store interface{}) error

// response
func (c Ctx) String(key string) error
func (c Ctx) JSON(data interface{}) error

// other method implementation here
```

**Comment by milhamsuryapratama** [comment]
yes, agree. we also have to follow the existing standardization in the existing Golang framework. a little suggest, a little advice, for naming `ctx`, it's better to use `Context` so that the naming is clearer

**Comment by born2ngopi** [comment]
i don't think so

> like most http router (Fiber, Echo)

i think fiber, echo is a web framework, but ngamux is only about http router. like [chi](https://github.com/go-chi/chi) or [mux](https://github.com/gorilla/mux)

**Comment by hadihammurabi** [comment]
> i don't think so
> 
> > like most http router (Fiber, Echo)
> 
> i think fiber, echo is a web framework, but ngamux is only about http router. like [chi](https://github.com/go-chi/chi) or [mux](https://github.com/gorilla/mux)

Alright.
So we can discuss about it then.

What do you think @milhamsuryapratama about what @born2ngopi said?

**Comment by milhamsuryapratama** [comment]
> > i don't think so
> > > like most http router (Fiber, Echo)
> > 
> > 
> > i think fiber, echo is a web framework, but ngamux is only about http router. like [chi](https://github.com/go-chi/chi) or [mux](https://github.com/gorilla/mux)
> 
> Alright.
> So we can discuss about it then.
> 
> What do you think @milhamsuryapratama about what @born2ngopi said?

First, I want to know the difference between a web framework and an HTTP router. can you explain it ?

because I don't find the difference between `mux` and `echo` let say, and I never use `mux` and I think `mux` and `echo` are the same

**Comment by born2ngopi** [comment]
The simple answer is feature, 

For example in web framework, there is many feature like bind request body, validation or simple api to render template like c.Render() on [fiber](https://docs.gofiber.io/guide/templates), etc. While http router only focuses on handling the router itself, like middleware, routing, and etc.

**Comment by hadihammurabi** [comment]
> The simple answer is feature,
> 
> For example in web framework, there is many feature like bind request body, validation or simple api to render template like c.Render() on [fiber](https://docs.gofiber.io/guide/templates), etc. While http router only focuses on handling the router itself, like middleware, routing, and etc.

Yes, i aggree. Better, as HTTP router, we don't change the handler.
